# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Added_Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_name', models.CharField(max_length=200)),
                ('apple_artist', models.CharField(max_length=200)),
                ('apple_id', models.CharField(max_length=200)),
                ('spotify_name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Missed_Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_name', models.CharField(max_length=200)),
                ('apple_artist', models.CharField(max_length=200)),
                ('apple_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('added_songs', models.ManyToManyField(to='spotify_convert.Added_Song')),
                ('missed_songs', models.ManyToManyField(to='spotify_convert.Missed_Song')),
            ],
        ),
    ]
