# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-11 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0002_auto_20170209_0358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Added_Song',
            new_name='AddedSong',
        ),
        migrations.RenameModel(
            old_name='Missed_Song',
            new_name='MissedSong',
        ),
        migrations.RenameModel(
            old_name='Spotify_User',
            new_name='SpotifyUser',
        ),
    ]
