# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify_convert', '0003_auto_20170211_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('spotify_user_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='addedsong',
            name='spotify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_convert.UserProfile'),
        ),
        migrations.AlterField(
            model_name='missedsong',
            name='spotify_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_convert.UserProfile'),
        ),
        migrations.DeleteModel(
            name='SpotifyUser',
        ),
    ]
