# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0004_auto_20170215_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_refresh',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_token',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
    ]
