# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0005_auto_20170215_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_refresh',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spotify_user_id',
            field=models.CharField(max_length=500),
        ),
    ]
