# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0006_auto_20170215_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='No Name', max_length=500),
            preserve_default=False,
        ),
    ]
