# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0008_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_expires_in',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
    ]
