# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0009_userprofile_spotify_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_expires_in',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spotify_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 17, 12, 1, 880464)),
            preserve_default=False,
        ),
    ]
