# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-15 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_convert', '0010_auto_20170215_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedsong',
            name='spotify_name',
        ),
    ]
